AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager Template for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  SecretsName:
    Description: Secrets Manager Name
    Type: String
    Default: /secrets/database-secrets
  AuroraDBUsername:
    NoEcho: 'true'
    Description: MasterUsername for Aurora PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

#Mappings: 
#Conditions: 

Resources: 
# Secrets Manager
# https://docs.aws.amazon.com/ja_jp/secretsmanager/latest/userguide/reference_secret_json_structure.html#reference_secret_json_structure_rds
  RDSSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretsName
      Description: RDS Aurora Secrets
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${AuroraDBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"      
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-RDS-SecretsManager
Outputs:
  RDSSecretsManagerName:
    Description: RDS Secrets Manager Name
    Value: !Ref SecretsName
    Export: 
      Name: !Sub ${StackPrefix}-RDSSecretsManagerName
  RDSSecretsManagerArn:
    Description: RDS Secrets Manager Arn
    Value: !Ref RDSSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-RDSSecretsManagerArn  