AWSTemplateFormatVersion: 2010-09-09
Description: ECS Task Definition Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-ecr.yaml, cfn-ecache-redis.yaml, cfn-rds-aurora.yaml, cfn-sqs.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Production
    ConstraintDescription: must be a prod or test
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for PostgreSQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  AppDataS3BucketName:
    Description: Location of S3 Bucket For Application Data
    Type: String
    Default: mysd33bucket123
Mappings: 
  FrontendAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container,xray"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container,xray"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container,xray"
  BackendServiceTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container,xray"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container,xray"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container,xray"
  BatchAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"      
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container"
  ScheduleLaunchAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"      
      "ContainerImage" : "sample-schedulelaunch:latest"
      "ContainerMemory" : 1024
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"                  
      "ContainerImage" : "sample-schedulelaunch:latest"
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"                  
      "ContainerImage" : "sample-schedulelaunch:latest"
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container"      
#Conditions: 

Resources:
  #Log Group
  FrontendFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-bff-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendFireLensLogGroup

  BackendFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-backend-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendFireLensLogGroup

  BatchFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-batch-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchFireLensLogGroup

  ScheduleLaunchFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-schedulelanuch-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-ScheduleLaunchFireLensLogGroup

  #ECS Task Definition for Frontend Application
  FrontendAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-frontend-app
      RequiresCompatibilities:
        - FARGATE
      Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-FrontendECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp                   
          PortMappings:
            - ContainerPort: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: API_BACKEND_URL
              Value: 
                Fn::Join: 
                  - ""
                  - - "http://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS
            - Name: DELAYED_BATCH_QUEUE
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName
            - Name: AWS_SQS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_S3_BUCKET
              Value: !Ref AppDataS3BucketName
            - Name: AWS_S3_REGION
              Value: !Ref AWS::Region
            - Name: SPRING_DATA_REDIS_HOST
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-ECachePrimaryEndPoint
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
          Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: frontend_log_router
          Image: 
            Fn::ImportValue: !Sub ${StackPrefix}-BffFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendAppECSTaskDefinition
  #ECS Task Definition for Backend Application
  BackendServiceECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-backend-app
      RequiresCompatibilities:
        - FARGATE        
      Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Cpu]      
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BackendECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerName]          
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp                   
          PortMappings:
            - ContainerPort: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]              
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Profile]
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword              
          Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: backend_log_router
          Image: 
            Fn::ImportValue: !Sub ${StackPrefix}-BackendFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendServiceECSTaskDefinition
  #ECS Task Definition for Batch Application
  BatchAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-batch-app
      RequiresCompatibilities:
        - FARGATE
      Memory: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BatchECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp                   
          PortMappings:
            - ContainerPort: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: AWS_SQS_LISTENER_QUEUENAME
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName             
            - Name: AWS_SQS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_S3_BUCKET
              Value: !Ref AppDataS3BucketName
            - Name: AWS_S3_REGION
              Value: !Ref AWS::Region              
            - Name: API_BACKEND_URL
              Value: 
                Fn::Join: 
                  - ""
                  - - "http://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS                
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
          Memory: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: batch_log_router
          Image: 
            Fn::ImportValue: !Sub ${StackPrefix}-BatchFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BatchFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchAppECSTaskDefinition
  #ECS Task Definition for ScheduleLaunch Application
  ScheduleLaunchAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-schedulelaunch-app
      RequiresCompatibilities:
        - FARGATE
      Memory: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ScheduleLaunchECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp                   
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: DELAYED_BATCH_QUEUES_SAMPLEBATCH_NAME
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName
            - Name: AWS_SQS_REGION
              Value: !Ref AWS::Region       
            - Name: BATCH_SCHEDULE_TARGETID
              Value: SB_001              
          Memory: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: batch_log_router
          Image: 
            Fn::ImportValue: !Sub ${StackPrefix}-ScheduleLaunchFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ScheduleLaunchFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-ScheduleLaunchAppECSTaskDefinition
Outputs:
  FrontendAppECSTaskDefinition:
    Description: Frontend ECS Task Definition
    Value: !Ref FrontendAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-FrontendECS-TaskDefinition
  BackendServiceECSTaskDefinition:
    Description: Backend ECS Task Definition
    Value: !Ref BackendServiceECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BackendECS-TaskDefinition
  BatchAppECSTaskDefinition:
    Description: Batch ECS Task Definition
    Value: !Ref BatchAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BatchECS-TaskDefinition
  ScheduleLaunchAppECSTaskDefinition:
    Description: ScheduleLaunch ECS Task Definition
    Value: !Ref ScheduleLaunchAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-ScheduleLaunchECS-TaskDefinition      