AWSTemplateFormatVersion: 2010-09-09
Description: CodeDeploy Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-alb.yaml, cfn-tg-bg.yaml, cfn-ecs-cluster.yaml, cfn-ecs-task.yaml, cfn-ecs-service.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo

#Mappings: 

#Conditions: 

Resources:
  #Code Deploy Application
  BackendCodeDeployApplication: 
    Type: AWS::CodeDeploy::Application 
    Properties:
      ComputePlatform: ECS
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendCodeDeployApplication

  #Code Deploy Deployment Group
  BackendCodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      ApplicationName: !Ref BackendCodeDeployApplication
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL      
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 0
      DeploymentConfigName: CodeDeployDefault.ECSLinear10PercentEvery1Minutes
      #DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      ECSServices:
        - ClusterName: 
            Fn::ImportValue: !Sub ${StackPrefix}-Backend-ECSCluster-Name
          ServiceName: 
            Fn::ImportValue: !Sub ${StackPrefix}-BackendService-Name
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-Listener
            #TestTrafficRoute                
            TargetGroups:
              - Name:
                  Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DefaultTargetGroupName
              - Name:
                  Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-TargetGroup2Name
      ServiceRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-CodeDeployServiceRole-Arn
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendCodeDeployDeploymentGroup
Outputs:
  BackendCodeDeployApplicationName: 
    Description: CodeDeploy Application Name
    Value: !Ref BackendCodeDeployApplication
    Export: 
      Name: !Sub ${StackPrefix}-Backend-CodeDeployAppName
  BackendCodeDeployDeploymentGroupName:
    Description: CodeDeploy Deployment Group Name
    Value: !Ref BackendCodeDeployDeploymentGroup
    Export: 
      Name: !Sub ${StackPrefix}-Backend-DeploymentGroupName
