AWSTemplateFormatVersion: 2010-09-09
Description: RDS Aurora PostgreSQL Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-vpc.yaml, cfn-sg.yaml, cfn-secrets.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  DBName:
    Description: Database Name
    Type: String
    Default: testdb
  DBEngineVersion:
    Description: Version number of the database engine
    Type: String
    Default: 16.4
  DBEngineFamily:
    Description: Family of the database engine
    Type: String
    Default: aurora-postgresql16
  #DBInstanceClassName:
  #  Description: DB Instance Class
  #  Type: String
  #  #https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.SupportAurora
  #  Default: db.t3.medium    
  #  #Default: db.r5.large
  AuroraServerlessMaxCapacity: 
    Description: Aurora Serverless V2 ScalingConfiguration MaxCapacity
    Type: Number
    Default: 2
  AuroraServerlessMinCapacity: 
    Description: Aurora Serverless V2 ScalingConfiguration MinCapacity
    Type: Number
    Default: 0.5

Resources:
# RDS Aurora
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${StackPrefix}-RDSDBSubnetGroup
      DBSubnetGroupDescription: Aurora for PostgreSQL DB Subnet group
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetThreeId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetFourId

  RDSDClusterBParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      DBClusterParameterGroupName: !Sub ${StackPrefix}-RDSDClusterBParameterGroup
      Description: RDS Aurora for PostgreSQL DB Parameter Group
      Family: !Ref DBEngineFamily
      # Reference To Create Customize Parameters Group 
      # https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Reference.ParameterGroups.html      
      Parameters:
        timezone: Asia/Tokyo

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: !Ref DBName
      #DBClusterParameterGroupName: !Sub default.${DBEngineFamily}
      DBClusterParameterGroupName: !Ref RDSDClusterBParameterGroup
      DBClusterIdentifier: aurora-postgresql-cluster
      DBSubnetGroupName: !Ref RDSDBSubnetGroup      
      EnableCloudwatchLogsExports:
        - postgresql
      Engine: aurora-postgresql
      EngineVersion: !Ref DBEngineVersion
      MasterUsername:  
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSSecretsManagerName
            - ":SecretString:username}}"
      MasterUserPassword: 
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSSecretsManagerName
            - ":SecretString:password}}"
      Port: 5432
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-AuroraSecurityGroup-ID          
      ServerlessV2ScalingConfiguration: 
        MaxCapacity: !Ref AuroraServerlessMaxCapacity
        MinCapacity: !Ref AuroraServerlessMinCapacity
    #TODO: Snapshot
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  RDSDBInstance1:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.serverless
      #DBInstanceClass: !Ref DBInstanceClassName      
      DBInstanceIdentifier: aurora-postgresql-instance1      
      Engine: aurora-postgresql
      PubliclyAccessible: false
    #TODO: Snapshot
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  
  RDSDBInstance2:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.serverless
      #DBInstanceClass: !Ref DBInstanceClassName
      DBInstanceIdentifier: aurora-postgresql-instance2      
      Engine: aurora-postgresql
      PubliclyAccessible: false
    #TODO:  Snapshot      
    UpdateReplacePolicy: Delete      
    DeletionPolicy: Delete

Outputs:
  RDSClusterID:
    Description: RDS Aurora Cluster ID
    Value: !Ref RDSCluster
    Export: 
      Name: !Sub ${StackPrefix}-RDSClusterID
  RDSClusterEndpointAddress:
    Description: RDS Aurora Cluster Endpoint Address
    Value: !GetAtt RDSCluster.Endpoint.Address
    Export: 
      Name: !Sub ${StackPrefix}-RDSClusterEndpointAddress
  RDSReaderEndpointAddress:
    Description: RDS AuroraReader Endpoint Address
    Value: !GetAtt RDSCluster.ReadEndpoint.Address
    Export: 
      Name: !Sub ${StackPrefix}-RDSReaderEndpointAddress
  RDSClusterEndpointPort:
    Description: RDS Aurora Cluster Endpoint Port
    Value: !GetAtt RDSCluster.Endpoint.Port
    Export: 
      Name: !Sub ${StackPrefix}-RDSClusterEndpointPort
  RDSDBName:
    Description: RDS Database Name
    Value: !Ref DBName
    Export: 
      Name: !Sub ${StackPrefix}-RDSDBName