AWSTemplateFormatVersion: 2010-09-09
Description: SSM Parameter Store Template for CloudFormation Demo. Depends on cfn-ecahce-valkey.yaml, cfn-rds-aurora.yaml, cfn-sqs.yaml, cfn-dynamodb.yaml, cfn-alb.yaml

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  ProjectName:
    Description: Project Name
    Type: String
    Default: example
  EnvName:
    Description: Environment Name
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]    
    Default: Production
  AppDataS3BucketName:
    Description: Location of S3 Bucket For Application Data
    Type: String
    Default: mysd33bucket123  
  # PostgreSQL Timeout Settings for Aurora Auto Pause
  # https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2-auto-pause.html#auto-pause-how-it-works
  # PostgreSQL Parameters
  # https://jdbc.postgresql.org/documentation/use/#connection-parameters
  PostgresConnectTimeout:
    Description: The timeout value used for socket connect operations. JDBC Driver default value is 10. max value is 2147484. 0 means timeout disabled.
    Type: String
    Default: "40"
#    Default: "30"


Resources:
  #common
  CommonSQSParameters:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.sqs.region
      Type: String
      Value: !Ref AWS::Region
  CommonS3RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.s3.region
      Type: String
      Value: !Ref AWS::Region
  CommonS3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.s3.bucket
      Type: String
      Value: !Ref AppDataS3BucketName
  CommonDynamoDBRegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.dynamodb.region
      Type: String
      Value: !Ref AWS::Region
  CommonDynamoDBTodoTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.dynamodb.todo-tablename
      Type: String
      Value:
        Fn::ImportValue: !Sub ${StackPrefix}-TodoTableName
  CommonRedisHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/spring.data.redis.host
      Type: String
      Value:
        Fn::ImportValue: !Sub ${StackPrefix}-ECachePrimaryEndPoint
  CommonRedisSSLEnabledParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/spring.data.redis.ssl.enabled
      Type: String
      Value: true
  CommonDatasourceUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/spring.datasource.url
      Type: String
      Value:
        Fn::Join: 
          - ""
          - - "jdbc:postgresql://"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
            - ":"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
            - "/"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - !Sub "?connectTimeout=${PostgresConnectTimeout}"
  CommonWriteDatasourceUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.datasource.write.url
      Type: String
      Value:
        Fn::Join: 
          - ""
          - - "jdbc:postgresql://"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
            - ":"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
            - "/"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - !Sub "?connectTimeout=${PostgresConnectTimeout}"
  CommonReadDatasourceUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.datasource.read.url
      Type: String
      Value:
        Fn::Join: 
          - ""
          - - "jdbc:postgresql://"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSReaderEndpointAddress
            - ":"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
            - "/"
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - !Sub "?connectTimeout=${PostgresConnectTimeout}"
  CommonApiBackendUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/common/example.api.backend.url
      Type: String
      Value: 
        Fn::Join: 
          - ""
          - - "http://"
            - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS            
  # sample-bff
  SampleBffTimeoutDurationParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-bff/resilience4j.timelimiter.configs.default.timeoutDuration
      Type: String
      Value: 3s            
  SampleBffAsyncQueueParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-bff/example.async.queue
      Type: String
      Value:
        Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName      
  SampleBffDatasourceDynamicRoutingParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-bff/example.datasource.dynamic-routing.enabled
      Type: String
      Value: true
  # sample-backend
  SampleBackendDatasourceDynamicRoutingParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-backend/example.datasource.dynamic-routing.enabled
      Type: String
      Value: true

  # sample-batch
  SampleBatchSqsListenerQueueNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-batch/example.sqs.listener.queue-name
      Type: String
      Value:
        Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName
  SampleBatchTimeoutDurationParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-batch/resilience4j.timelimiter.configs.default.timeoutDuration
      Type: String
      Value: 3s
  #sample-schedulelaunch
  SampleScheduleLaunchBatchQueuesSampleBatchNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${ProjectName}/${EnvName}/sample-schedulelaunch/example.batch.queues.samplebatch.name
      Type: String
      Value:
        Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName
