AWSTemplateFormatVersion: 2010-09-09
Description: ECS Task Definition Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-ecr.yaml, cfn-ssm-param.yaml.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Production
    ConstraintDescription: must be a prod or test
Mappings: 
  FrontendAppTaskDefinitionMap:
    Production:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "Profile" : "production,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Staging:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "Profile" : "staging,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Dev:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "Profile" : "dev,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
  BackendServiceTaskDefinitionMap:
    Production:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "Profile" : "production,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Staging:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "Profile" : "staging,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Dev:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "Profile" : "dev,log_container,xray"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
  BatchAppTaskDefinitionMap:
    Production:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-batch-app"      
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "Profile" : "production,log_container"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Staging:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "Profile" : "staging,log_container"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
    Dev:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "Profile" : "dev,log_container"
      "HealthCheck" : "curl -f http://localhost:8080/actuator/health || exit 1"
  ScheduleLaunchAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"      
      "ContainerImage" : "sample-schedulelaunch:latest"
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"                  
      "ContainerImage" : "sample-schedulelaunch:latest"
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-schedulelaunch-app"                  
      "ContainerImage" : "sample-schedulelaunch:latest"
      "Profile" : "dev,log_container"      
#Conditions: 

Resources:
  #Log Group
  FrontEndAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-bff-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontEndAppECSLogGroup

  BackendAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-backend-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendAppECSLogGroup

  BatchAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-batch-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchAppECSLogGroup

  ScheduleLaunchAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-schedulelanuch-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-ScheduleLaunchAppECSLogGroup

  #ECS Task Definition for Frontend Application
  FrontendAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-frontend-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-FrontendECSTaskRole-Arn
      Volumes:
        - Name: tmp
      ContainerDefinitions:
        - Name: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp              
          PortMappings:
            - ContainerPort: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          HealthCheck:
            Command:
              - CMD-SHELL
              - !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, HealthCheck]
            Interval: 150
            StartPeriod: 300
          Environment:
            - Name: TZ
              Value: Asia/Tokyo
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_PARAMETERSTORE
              Value: DEBUG
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_SECRETSMANAGER
              Value: DEBUG
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontEndAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendAppECSTaskDefinition
  #ECS Task Definition for Backend Application
  BackendServiceECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-backend-app
      RequiresCompatibilities:
        - EC2        
      Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Cpu]      
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BackendECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerName]          
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp                
              ContainerPath: /tmp              
          PortMappings:
            - ContainerPort: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]              
          HealthCheck:
            Command:
              - CMD-SHELL
              - !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, HealthCheck]
            Interval: 60
            StartPeriod: 120
          Environment:
            - Name: TZ
              Value: Asia/Tokyo          
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Profile]
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_PARAMETERSTORE
              Value: DEBUG
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_SECRETSMANAGER
              Value: DEBUG              
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendServiceECSTaskDefinition
  #ECS Task Definition for Batch Application
  BatchAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-batch-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BatchECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp                
              ContainerPath: /tmp              
          PortMappings:
            - ContainerPort: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          HealthCheck:
            Command:
              - CMD-SHELL
              - !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, HealthCheck]
            Interval: 60
            StartPeriod: 60
          Environment:
            - Name: TZ
              Value: Asia/Tokyo           
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Profile]                           
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_PARAMETERSTORE
              Value: DEBUG
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_SECRETSMANAGER
              Value: DEBUG              
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BatchAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchAppECSTaskDefinition
  #ECS Task Definition for ScheduleLaunch Application
  ScheduleLaunchAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-schedulelaunch-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ScheduleLaunchECSTaskRole-Arn
      Volumes:
        - Name: tmp        
      ContainerDefinitions:
        - Name: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          ReadonlyRootFilesystem: true
          MountPoints:
            - SourceVolume: tmp                
              ContainerPath: /tmp              
          Environment:
            - Name: TZ
              Value: Asia/Tokyo           
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [ScheduleLaunchAppTaskDefinitionMap, !Ref EnvironmentType, Profile]             
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_PARAMETERSTORE
              Value: DEBUG
            - Name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_SECRETSMANAGER
              Value: DEBUG              
            - Name: EXAMPLE_BATCH_SCHEDULE_TARGETID
              Value: SB_001
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ScheduleLaunchAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-ScheduleLaunchAppECSTaskDefinition
Outputs:
  FrontendAppECSTaskDefinition:
    Description: Frontend ECS Task Definition
    Value: !Ref FrontendAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-FrontendECS-TaskDefinition
  BackendServiceECSTaskDefinition:
    Description: Backend ECS Task Definition
    Value: !Ref BackendServiceECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BackendECS-TaskDefinition
  BatchAppECSTaskDefinition:
    Description: Batch ECS Task Definition
    Value: !Ref BatchAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BatchECS-TaskDefinition
  ScheduleLaunchAppECSTaskDefinition:
    Description: ScheduleLaunch ECS Task Definition
    Value: !Ref ScheduleLaunchAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-ScheduleLaunchECS-TaskDefinition      