AWSTemplateFormatVersion: 2010-09-09
Description: CodeBuild Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-ecr.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  ProjectName:
    Description: CodeBuild Project Name
    Type: String
    Default: demo-backend-ci
  CodeBuildEnvType:
    Description: CodeBuild Environment Type
    Type: String
    #Default: ARM_CONTAINER
    Default: LINUX_CONTAINER    
  CodeBuildImage:
    Description: CodeBuild Environment Image
    Type: String
    #Default: aws/codebuild/amazonlinux-aarch64-standard:3.0
    Default: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  RepositoryName:
    Description: Source Code Repository Location of CodeCommit
    Type: String
    #Default: backend
    Default: sample-backend
  BranchName:
    Description: CodeCommit branch name
    Type: String
    Default: main    
  ArtifactS3BucketName:
    Description: Artifact Location of S3 Bucket
    Type: String
    Default: mysd33bucket123
  CacheS3Location:
    Description: Artifact Location of S3 Bucket Name/Prefix
    Type: String
    Default: mysd33bucket123/cache
    
#Mappings: 

#Conditions: 

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:      
      Name: !Sub ${ProjectName}
      Description: Backend CI Project
      Source:
        Type: CODECOMMIT
        Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepositoryName}
      SourceVersion: !Ref BranchName
      Artifacts:
        Type: S3
        Location: !Sub ${ArtifactS3BucketName}
      BadgeEnabled: true
      Environment:
        Type: !Ref CodeBuildEnvType
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ECR_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: REPOSITORY_URI
            Value:
              Fn::ImportValue: !Sub ${StackPrefix}-BackendECRRepositoryUri
          - Name: ECS_TASK_DEFINITION
            Value: !Sub ${StackPrefix}-ecstask-backend-app
          - Name: ECS_CONTAINER_NAME
            Value: !Sub ecsdemo-backend-service
      ServiceRole:
        Fn::ImportValue: !Sub ${StackPrefix}-CodeBuildRole-Arn
      TimeoutInMinutes: 10
      Cache:
        #Type: LOCAL
        #Modes:
        #  - LOCAL_CUSTOM_CACHE
        Type: S3
        Location: !Ref CacheS3Location
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
Outputs:
  CodeBuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref ProjectName
    Export: 
      Name: !Sub ${StackPrefix}-Backend-CodeBuildProjectName