AWSTemplateFormatVersion: 2010-09-09
Description: VPCEndpoint Template for CloudFormation Demo. Depends on cfn-vpc.yaml, cfn-sg.yaml.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo 
  
#Mappings: 

#Conditions: 

Resources:
# DynamoDB VPC Endoint 
  DynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID
      RouteTableIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateRouteTableId
        
# S3 VPC Endpoint
  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Gateway
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID
      RouteTableIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateRouteTableId

# SQS VPC Endpoint
  SQSVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sqs
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID                      
      PrivateDnsEnabled: true

# CloudWatch Logs VPC Endpoint
  CloudWatchLogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID                      
      PrivateDnsEnabled: true

# CloudFormation VPC Endpoint for ECS on EC2 (cfn-signal from ECS on EC2 to Cloudformation)
  CfnVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.cloudformation
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

# ECS VPC Endpoints for ECS on EC2 (docker pull from ECS on EC2 to ECR)
  ECSAgentVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecs-agent
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

  ECSTelemetryVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecs-telemetry
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

  ECSVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecs
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

# ECR VPC Endpoint
  ECRApiVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

  ECRDkrVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID
      PrivateDnsEnabled: true

#X-Ray VPC Endpoint
  XRayVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.xray
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID
      PrivateDnsEnabled: true 

#Systems Manager (Parameter Store) VPC Endpoint
  SSMParamVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID
      PrivateDnsEnabled: true

#Secrets Manager VPC Endpoint
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID
      PrivateDnsEnabled: true  

#Outputs: