AWSTemplateFormatVersion: 2010-09-09
Description: ECS Task Definition Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-ecr.yaml, cfn-ecache-redis.yaml, cfn-rds-aurora.yaml, cfn-sqs.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Production
    ConstraintDescription: must be a prod or test
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for PostgreSQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  AppDataS3BucketName:
    Description: Location of S3 Bucket For Application Data
    Type: String
    Default: mysd33bucket123
Mappings: 
  FrontendAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      #"ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container,xray"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      #"ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container,xray"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      #"ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerImage" : "sample-bff:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container,xray"
  BackendServiceTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      #"ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container,xray"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      #"ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container,xray"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      #"ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerImage" : "sample-backend:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container,xray"
  BatchAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"      
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-batch-app"                  
      "ContainerImage" : "sample-batch:latest"
      "ContainerPort" : 8080
      "ContainerMemory" : 1024
      "Profile" : "dev,log_container"
#Conditions: 

Resources:
  #Log Group
  FrontEndAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-bff-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontEndAppECSLogGroup

  BackendAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-backend-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendAppECSLogGroup

  BatchAppECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-batch-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchAppECSLogGroup

  #ECS Task Definition for Frontend Application
  FrontendAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-frontend-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-FrontendECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          PortMappings:
            - ContainerPort: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: API_BACKEND_URL
              Value: 
                Fn::Join: 
                  - ""
                  - - "http://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS
            - Name: DELAYED_BATCH_QUEUE
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName
            - Name: AWS_SQS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_S3_BUCKET
              Value: !Ref AppDataS3BucketName
            - Name: AWS_S3_REGION
              Value: !Ref AWS::Region
            - Name: SPRING_REDIS_HOST
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-ECachePrimaryEndPoint
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpoint
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
          Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontEndAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendAppECSTaskDefinition
  #ECS Task Definition for Backend Application
  BackendServiceECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-backend-app
      RequiresCompatibilities:
        - EC2        
      Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Cpu]      
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BackendECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerName]          
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          PortMappings:
            - ContainerPort: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]              
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Profile]
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpoint
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword              
          Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendServiceECSTaskDefinition
  #ECS Task Definition for Batch Application
  BatchAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-batch-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BatchECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          PortMappings:
            - ContainerPort: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: AWS_SQS_LISTENER_QUEUENAME
              Value:
                Fn::ImportValue: !Sub ${StackPrefix}-SQSQueueName             
            - Name: AWS_SQS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_S3_BUCKET
              Value: !Ref AppDataS3BucketName
            - Name: AWS_S3_REGION
              Value: !Ref AWS::Region              
            - Name: API_BACKEND_URL
              Value: 
                Fn::Join: 
                  - ""
                  - - "http://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS                
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpoint
                    - "/"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUsername 
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
          Memory: !FindInMap [BatchAppTaskDefinitionMap, !Ref EnvironmentType, ContainerMemory]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BatchAppECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix
        - Name: xray-daemon
          Image:
            Fn::ImportValue: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri
          Cpu: 32
          MemoryReservation: 256          
          PortMappings:
            - ContainerPort: 2000              
              Protocol: udp
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BatchAppECSTaskDefinition
Outputs:
  FrontendAppECSTaskDefinition:
    Description: Frontend ECS Task Definition
    Value: !Ref FrontendAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-FrontendECS-TaskDefinition
  BackendServiceECSTaskDefinition:
    Description: Backend ECS Task Definition
    Value: !Ref BackendServiceECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BackendECS-TaskDefinition
  BatchAppECSTaskDefinition:
    Description: Batch ECS Task Definition
    Value: !Ref BatchAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BatchECS-TaskDefinition