AWSTemplateFormatVersion: 2010-09-09
Description: ECR Template for CloudFormation Demo
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  BffRepositoryName:
    Description: Bff App Repository Name
    Type: String
    #Default: mynavi-sample-ecs-bff
    Default: sample-bff
  BackendRepositoryName:
    Description: Backend App Repository Name
    Type: String
    #Default: mynavi-sample-ecs-backend
    Default: sample-backend
  BffFluentBitRepositoryName:
    Description: Bff Sidecar Fluent Bit Repository Name
    Type: String
    Default: fluent-bit-bff
  BackendFluentBitRepositoryName:
    Description: Backend Sidecar Fluent Bit Repository Name
    Type: String
    Default: fluent-bit-backend
  XRayDaemonRepositoryName:
    Description: X-Ray Daemon Repository Name
    Type: String
    Default: xray-daemon

#Mappings: 

#Conditions: 

Resources: 
  #Repository for App 
  BffECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BffRepositoryName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BffECRRepository
  BackendECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BackendRepositoryName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendECRRepository
  #Repository for Sidecar FluentBit
  BffFluentBitECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BffFluentBitRepositoryName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BffFluentBitECRRepository
  BackendFluentBitECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BackendFluentBitRepositoryName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackFluentBitECRRepository
  XRayDaemonECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref XRayDaemonRepositoryName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-XRayDaemonRepository
Outputs:
  BffECRRepositoryArn:
    Description: Bff App Repository Arn
    Value: !GetAtt BffECRRepository.Arn
  BffECRRepositoryUri:
    Description: Bff App Repository URI
    Value: !GetAtt BffECRRepository.RepositoryUri
    Export:
      Name: !Sub ${StackPrefix}-BffECRRepositoryUri
  BackendECRRepositoryArn:
    Description: Backend App Repository Arn
    Value: !GetAtt BackendECRRepository.Arn    
  BackendECRRepositoryUri:
    Description: Backend App Repository URI
    Value: !GetAtt BackendECRRepository.RepositoryUri
    Export:
      Name: !Sub ${StackPrefix}-BackendECRRepositoryUri
  BffFluentBitECRRepositoryArn:
    Description: Bff Sidecar Fluent Bit Repository Arn
    Value: !GetAtt BffFluentBitECRRepository.Arn    
  BffFluentBitECRRepositoryUri:
    Description:  Bff Sidecar Fluent Bit Repository URI
    Value: !GetAtt BffFluentBitECRRepository.RepositoryUri
    Export:
      Name: !Sub ${StackPrefix}-BffFluentBitECRRepositoryUri
  BackendFluentBitECRRepositoryArn:
    Description: Backend Sidecar Fluent Bit Repository Arn
    Value: !GetAtt BackendFluentBitECRRepository.Arn    
  BackendFluentBitECRRepositoryUri:
    Description:  Backend Sidecar Fluent Bit Repository URI
    Value: !GetAtt BackendFluentBitECRRepository.RepositoryUri
    Export:
      Name: !Sub ${StackPrefix}-BackendFluentBitECRRepositoryUri      
  XRayDaemonECRRepositoryArn:  
    Description: X-Ray Daemon Repository Arn
    Value: !GetAtt XRayDaemonECRRepository.Arn    
  XRayDaemonECRRepositoryUri:
    Description:  X-Ray Daemon Repository URI
    Value: !GetAtt XRayDaemonECRRepository.RepositoryUri
    Export:
      Name: !Sub ${StackPrefix}-XRayDaemonECRRepositoryUri    