AWSTemplateFormatVersion: 2010-09-09
Description: ECS Task Definition Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-ecr.yaml
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Production
    ConstraintDescription: must be a prod or test

Mappings: 
  FrontendAppTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerPort" : 8080
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerPort" : 8080            
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-frontend-app"
      "ContainerImage" : "mynavi-sample-ecs-bff:latest"
      "ContainerPort" : 8080
      "Profile" : "dev,log_container"
  BackendServiceTaskDefinitionMap:
    Production:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerPort" : 8080      
      "Profile" : "production,log_container"
    Staging:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerPort" : 8080      
      "Profile" : "staging,log_container"
    Dev:
      "Memory" : 1024
      "Cpu" : 512
      "ContainerName" : "ecsdemo-backend-service"
      "ContainerImage" : "mynavi-sample-ecs-backend:latest"
      "ContainerPort" : 8080      
      "Profile" : "dev,log_container"

#Conditions: 

Resources:
  #Log Group
  FrontendFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-bff-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendFireLensLogGroup

  BackendFireLensLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/fluentbit-backend-sidecar"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendFireLensLogGroup

  #ECS Task Definition for Frontend Application
  FrontendAppECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-frontend-app
      RequiresCompatibilities:
        - EC2
      Memory: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-FrontendECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          PortMappings:
            - ContainerPort: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          Environment:
            - Name: ENV_TYPE
              Value: !FindInMap [FrontendAppTaskDefinitionMap, !Ref EnvironmentType, Profile]            
            - Name: BACKEND_URL
              Value: 
                Fn::Join: 
                  - ""
                  - - "http://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-PrivALB-DNS 
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: frontend_log_router
          Image: 
              Fn::ImportValue: !Sub ${StackPrefix}-BffFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix              
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FrontendAppECSTaskDefinition
  #ECS Task Definition for Backend Application
  BackendServiceECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-ecstask-backend-app
      RequiresCompatibilities:
        - EC2        
      Memory: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Cpu]      
      NetworkMode: awsvpc      
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-BackendECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerName]          
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          PortMappings:
            - ContainerPort: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]              
          Environment:
            - Name: ENV_TYPE
              Value: !FindInMap [BackendServiceTaskDefinitionMap, !Ref EnvironmentType, Profile]          
          LogConfiguration:
            LogDriver: awsfirelens
        - Name: backend_log_router
          Image: 
              Fn::ImportValue: !Sub ${StackPrefix}-BackendFluentBitECRRepositoryUri
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendFireLensLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref StackPrefix          
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BackendServiceECSTaskDefinition
Outputs:
  FrontendAppECSTaskDefinition:
    Description: Frontend ECS Task Definition
    Value: !Ref FrontendAppECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-FrontendECS-TaskDefinition
  BackendServiceECSTaskDefinition:
    Description: Backend ECS Task Definition
    Value: !Ref BackendServiceECSTaskDefinition
    Export:
      Name: !Sub ${StackPrefix}-BackendECS-TaskDefinition